# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convent_ware.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nums_label = QtWidgets.QLabel(self.centralwidget)
        self.nums_label.setGeometry(QtCore.QRect(280, 140, 140, 40))
        self.nums_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nums_label.setObjectName("nums_label")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(90, 210, 120, 40))
        self.submit_button.setObjectName("submit_button")
        self.input_dir_button = QtWidgets.QPushButton(self.centralwidget)
        self.input_dir_button.setGeometry(QtCore.QRect(40, 80, 120, 40))
        self.input_dir_button.setObjectName("input_dir_button")
        self.input_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.input_file_button.setGeometry(QtCore.QRect(40, 20, 120, 40))
        self.input_file_button.setObjectName("input_file_button")
        self.save_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_path_button.setGeometry(QtCore.QRect(40, 140, 120, 40))
        self.save_path_button.setObjectName("save_path_button")
        self.target_format_box = QtWidgets.QComboBox(self.centralwidget)
        self.target_format_box.setGeometry(QtCore.QRect(390, 80, 140, 40))
        self.target_format_box.setObjectName("target_format_box")
        self.target_format_label = QtWidgets.QLabel(self.centralwidget)
        self.target_format_label.setGeometry(QtCore.QRect(300, 80, 80, 40))
        self.target_format_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.target_format_label.setObjectName("target_format_label")
        self.process_type_box = QtWidgets.QComboBox(self.centralwidget)
        self.process_type_box.setGeometry(QtCore.QRect(390, 20, 140, 40))
        self.process_type_box.setObjectName("process_type_box")
        self.process_type_label = QtWidgets.QLabel(self.centralwidget)
        self.process_type_label.setGeometry(QtCore.QRect(300, 20, 80, 40))
        self.process_type_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.process_type_label.setObjectName("process_type_label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(310, 210, 180, 40))
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.nums_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.nums_doubleSpinBox.setGeometry(QtCore.QRect(430, 140, 100, 40))
        self.nums_doubleSpinBox.setObjectName("nums_doubleSpinBox")
        self.input_file_label = QtWidgets.QLabel(self.centralwidget)
        self.input_file_label.setGeometry(QtCore.QRect(170, 20, 100, 40))
        self.input_file_label.setText("")
        self.input_file_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_file_label.setObjectName("input_file_label")
        self.input_dir_label = QtWidgets.QLabel(self.centralwidget)
        self.input_dir_label.setGeometry(QtCore.QRect(170, 80, 100, 40))
        self.input_dir_label.setText("")
        self.input_dir_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_dir_label.setObjectName("input_dir_label")
        self.save_path_label = QtWidgets.QLabel(self.centralwidget)
        self.save_path_label.setGeometry(QtCore.QRect(170, 140, 100, 40))
        self.save_path_label.setText("")
        self.save_path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.save_path_label.setObjectName("save_path_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nums_label.setText(_translate("MainWindow", "每秒数量/GIF总数"))
        self.submit_button.setText(_translate("MainWindow", "转换"))
        self.input_dir_button.setText(_translate("MainWindow", "导入文件夹"))
        self.input_file_button.setText(_translate("MainWindow", "导入文件"))
        self.save_path_button.setText(_translate("MainWindow", "保存地址"))
        self.target_format_label.setText(_translate("MainWindow", "保存格式"))
        self.process_type_label.setText(_translate("MainWindow", "处理类型"))
